version: "3"
services:
  integration-deps:
    image: busybox
    depends_on:
      lnd1:
        condition: service_healthy
      lnd2:
        condition: service_healthy
  bitcoind:
    image: lncm/bitcoind:v22.0
    ports:
      - "18443:18443"
    volumes:
    - ${PWD}/dev/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
  lnd1:
    image: lightninglabs/lnd:v0.14.2-beta
    # ports:
    #   - "10009:10009"
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
    depends_on: [bitcoind]
    healthcheck:
      test: ["CMD-SHELL", "lncli -n regtest getinfo"]
      interval: 2s
      timeout: 2s
      retries: 5
  lnd2:
    image: lightninglabs/lnd:v0.14.2-beta
    # ports:
    #   - "10010:10009"
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
    depends_on: [bitcoind]
    healthcheck:
      test: ["CMD-SHELL", "lncli -n regtest getinfo"]
      interval: 2s
      timeout: 2s
      retries: 5
