[package]
name = "lnctl-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.27", features = ["use-serde"] }
uuid = { version = "0.8", features = ["v4"] }
